var num1=prompt(num1);
var num2=prompt(num2);
var suma=parseInt(num1) + parseInt(num2);
var resta=parseInt(num1) - parseInt(num2);
var mult=parseInt(num1) * parseInt(num2);
var div=parseInt(num1) / parseInt(num2);
console.log(suma);
console.log(resta);
console.log(mult);
console.log(div);
